# Generated by Django 4.1.7 on 2023-03-09 04:42

import assets.models.assest_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_stock',
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(default=assets.models.assest_model.maintain_serial, editable=False, primary_key=True, serialize=False),
        ),
    ]
