# Generated by Django 4.1.7 on 2023-03-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_company_website_alter_asset_model_alter_asset_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='company_name',
            new_name='company_id',
        ),
    ]
