# Generated by Django 4.1.7 on 2023-03-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_company_name_asset_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='model',
            new_name='asset_model',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='company_id',
            new_name='asset_of_company_id',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='stock',
            new_name='asset_stock',
        ),
    ]
