# Generated by Django 4.1.7 on 2023-03-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgethandout',
            name='is_checked_out',
            field=models.BooleanField(default=True),
        ),
    ]
