# Generated by Django 4.1.7 on 2023-03-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('employee', '0002_alter_employee_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgethandout',
            name='employer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.company'),
        ),
    ]
